version: '3'
# Define volumes for Databases
#
volumes:
  mqtt-pgdata:
  grafana-pgdata:

# Define services
#
services:

  # MQTT Server (MOSCA)
  #
  mqtt-server:
    image: matteocollina/mosca
    ports:
      - "1883:1883"

  # Storage (Postgres)
  #
  mqtt-storage:
    image: postgres:10-alpine
    volumes:
      - mqtt-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=omeglast

  # Grafana dedicated storage
  #
  grafana-storage:
    image: postgres:10-alpine
    volumes:
      - ./sql/grafana:/docker-entrypoint-initdb.d
      - grafana-pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${GRAFANA_POSTGRES_PASSWORD}
      - POSTGRES_USER=admin
      - POSTGRES_DB=grafana

  # Grafana Server
  #
  grafana:
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    depends_on:
      - grafana-storage
      - mqtt-storage
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-storage
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=admin
      - GF_DATABASE_PASSWORD=${GRAFANA_POSTGRES_PASSWORD}

  # MQTT Backend Server
  #
  mqtt-backend:
    image: jeckel/omeglast-mqtt-backend:latest
    depends_on:
      - mqtt-server
      - mqtt-storage
    environment:
      - MQTT_HOST=mqtt-server
      - MQTT_PORT=1883
      - POSTGRES_HOST=mqtt-storage
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=omeglast
