version: '3'
services:

  # MQTT Server (MOSCA)
  #
  mqtt_server:
    image: matteocollina/mosca
    ports:
      - "1883:1883"

  # Storage (Postgres)
  #
  storage:
    image: postgres:10-alpine
    volumes:
      - ../storage-postgreSQL/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin

  # Grafana dedicated storage
  #
  grafana-storage:
    image: postgres:10-alpine
    volumes:
      - ./sql/grafana:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=grafana

  # Grafana Server
  #
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - storage
    environment:
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_HOST=grafana-storage
      #- GF_DATABASE_HOST=storage
      - GF_DATABASE_NAME=grafana
      - GF_DATABASE_USER=admin
      - GF_DATABASE_PASSWORD=admin

  # IOT Server
  #
  server:
    image: node:8-alpine
    volumes:
      - ../server:/app
    working_dir: /app
    command: npm start
    depends_on:
      - mqtt_server
      - storage
    environment:
      - MQTT_HOST=mqtt_server
      - MQTT_PORT=1883
      - POSTGRES_HOST=storage
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=omeglast

  # Weather client for Paris
  #
  weather-paris:
    image: node:8-alpine
    volumes:
      - ../weather-client:/app
    working_dir: /app
    command: npm start
    depends_on:
      - mqtt_server
    environment:
      - MQTT_HOST=mqtt_server
      - MQTT_PORT=1883
      - WEATHER_LOCATION=Paris, FR
      - PUSH_INTERVAL=15000
      - TEMPERATURE_TOPIC=sensor/weather/paris/temperature
      - HUMIDITY_TOPIC=sensor/weather/paris/humidity

  # Weather client for Santiago
  #
  weather-santiago:
    image: node:8-alpine
    volumes:
      - ../weather-client:/app
    working_dir: /app
    command: npm start
    depends_on:
      - mqtt_server
    environment:
      - MQTT_HOST=mqtt_server
      - MQTT_PORT=1883
      - WEATHER_LOCATION=Santiago, CL
      - PUSH_INTERVAL=15000
      - TEMPERATURE_TOPIC=sensor/weather/santiago/temperature
      - HUMIDITY_TOPIC=sensor/weather/santiago/humidity

  # Storage UI
  #
  adminer:
    image: adminer
    ports:
      - "8081:8080"
