version: '2'
# Define volumes for Databases
#
volumes:
  mqtt-pgdata:
  grafana-pgdata:

# Define services
#
services:

  # MQTT Server (MOSCA)
  #
  mqtt-server:
    extends:
      file: compose/mqtt.yml
      service: mqtt-server

  # Storage (Postgres)
  #
  mqtt-storage:
    extends:
      file: compose/mqtt.yml
      service: mqtt-storage
    volumes:
      - mqtt-pgdata:/var/lib/postgresql/data

  # Grafana dedicated storage
  #
  grafana-storage:
    extends:
      file: compose/grafana.yml
      service: grafana-storage
    volumes:
      - grafana-pgdata:/var/lib/postgresql/data

  # Grafana Server
  #
  grafana:
    extends:
      file: compose/grafana.yml
      service: grafana
    depends_on:
      - grafana-storage
      - mqtt-storage

  # MQTT Backend Server
  #
  mqtt-backend:
    extends:
      file: compose/mqtt.yml
      service: mqtt-backend-dev
    depends_on:
      - mqtt-server
      - mqtt-storage

  # Weather client for Paris
  #
  weather-paris:
    extends:
      file: compose/weather.yml
      service: weather-client-dev
    depends_on:
      - mqtt-server
    environment:
      - WEATHER_LOCATION=Paris, FR
      - TEMPERATURE_TOPIC=sensor/weather/paris/temperature
      - HUMIDITY_TOPIC=sensor/weather/paris/humidity

  # Weather client for Santiago
  #
  weather-santiago:
    extends:
      file: compose/weather.yml
      service: weather-client-dev
    depends_on:
      - mqtt-server
    environment:
      - WEATHER_LOCATION=Santiago, CL
      - TEMPERATURE_TOPIC=sensor/weather/santiago/temperature
      - HUMIDITY_TOPIC=sensor/weather/santiago/humidity

  # Storage UI
  #
  adminer:
    image: adminer
    ports:
      - "8081:8080"
